adjective = input("Enter an adjective ")
adjective_2 = input("Enter another adjective ")
bird_type = input("Enter a type of bird")
room_in_a_house = input("Enter a room in a house eg: kitchen, bathroom... etc.   ")
verb_past_tense = input("Enter a past tense verb ")
verb = input("Enter a verb")
relative_name = input("Enter your relative's name")
noun = input("Enter a noun")
a_liquid = input("Enter a liquid eg: water, oil, alcohol")
verb_ing = input("Enter a verb ending with -ing")
body_part = input("Enter a body part eg: hand, shoulder, head")
plural_noun = input("Enter a plural noun")
verb_ing2 = input("Enter another verb ending with -ing")
noun_2 = input("Enter a noun")



print("It was a " + adjective + ", cold November day. I\n woke up to the " + adjective_2 + " smell of " + bird_type)
print("roasting in the " + room_in_a_house + " downstairs. I")
print(verb_past_tense + " down the stairs to see if I could")
print("help " + verb + " the dinner. My mom said,")
print("\"See if " + relative_name + " needs a fresh " + noun + ".So I")
print("carried a tray of glasses full of " + a_liquid + " into")
print("the " + verb_ing + " room. When I got there , I")
print("couldn't believe my " + body_part + " ! There were")
print( plural_noun + verb_ing2 + " on the " + noun_2 + "!")